i1=input('enter first number:')
i2=input('enter second number:')
a=float(i1)
b=float(i2)
print('add=',a+b)
print('sub',a-b)
print('mul=',a*b)
print('div=',a/b)
print('rem=',a%b)
print('exp=',a**b)
print('floor div=',a//b)
